services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: desafio-desenvolvedor-app
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
    depends_on:
      - mongodb
    environment:
      - DB_CONNECTION=mongodb
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_DATABASE=desafio
      - DB_USERNAME=zero
      - DB_PASSWORD=Suav!dad3

  mongodb:
    image: mongo
    container_name: desafio-desenvolvedor-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: zero
      MONGO_INITDB_ROOT_PASSWORD: Suav!dad3
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata: